"""revision inicial

Revision ID: 863e933f6b88
Revises: 
Create Date: 2024-10-01 12:40:12.285346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863e933f6b88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=80), nullable=False),
        sa.Column('direccion', sa.String(length=120), nullable=True),
        sa.Column('telefonos', sa.String(length=50), nullable=True),
        sa.Column('fecha_nac', sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contactos')
    # ### end Alembic commands ###
