"""agrega direccion de nuevo

Revision ID: d4cae5eb8efd
Revises: da4d3f2d3d0b
Create Date: 2024-10-01 16:30:17.259823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4cae5eb8efd'
down_revision: Union[str, None] = 'da4d3f2d3d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactos', sa.Column('calle', sa.String(length=80), nullable=True))
    op.add_column('contactos', sa.Column('numero', sa.Integer(), nullable=True))
    op.add_column('contactos', sa.Column('piso', sa.Integer(), nullable=True))
    op.add_column('contactos', sa.Column('depto', sa.String(length=10), nullable=True))
    op.add_column('contactos', sa.Column('localidad_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contactos', 'localidades', ['localidad_id'], ['id'])
    op.drop_column('contactos', 'direccion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactos', sa.Column('direccion', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contactos', type_='foreignkey')
    op.drop_column('contactos', 'localidad_id')
    op.drop_column('contactos', 'depto')
    op.drop_column('contactos', 'piso')
    op.drop_column('contactos', 'numero')
    op.drop_column('contactos', 'calle')
    # ### end Alembic commands ###
