"""agrega direccion

Revision ID: da4d3f2d3d0b
Revises: 3ab4efec0ad3
Create Date: 2024-10-01 16:11:11.512481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4d3f2d3d0b'
down_revision: Union[str, None] = '3ab4efec0ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
